parameters:
    escape_hither.indexer.class: EscapeHither\SearchManagerBundle\EventListener\IndexerListener
    escapehither.search_request_parameter_handler.class: EscapeHither\SearchManagerBundle\Services\RequestParameterHandler
    escapehither.search_request_handler.class: EscapeHither\SearchManagerBundle\Services\SearchRequestHandler


services:
    #TODO MAKE SOME PRIVATE
    _defaults: { public: true }

    escapehither.doctrine_indexer_listener:
            class: '%escape_hither.indexer.class%'
            arguments: ["%escape_hither.search_manager.indexes%", "%escape_hither.search_manager.host%", "@doctrine.orm.entity_manager"]
            tags:
                - { name: doctrine.event_listener, event: postPersist }
                - { name: doctrine.event_listener, event: postUpdate }
                - { name: doctrine.event_listener, event: postLoad }
                - { name: doctrine.event_listener, event: preRemove }

    escapehither.search_request_parameter_handler:
            class: "%escapehither.search_request_parameter_handler.class%"
            arguments: ["@request_stack","@service_container"]
            
    escapehither.search_request_handler:
            class: "%escapehither.search_request_handler.class%"
            arguments: ["@escapehither.search_request_parameter_handler", "%escape_hither.search_manager.host%", "%escape_hither.search_manager.indexes%"]
